name       : haskell-neat-interpolation
version    : 0.3.2.1
release    : 2
source     :
    - http://hackage.haskell.org/package/neat-interpolation-0.3.2.1/neat-interpolation-0.3.2.1.tar.gz : 5530e43ca4de09b972d173e522f9dc96265f3afe0df695a25f0141be816fa014
license    : MIT
component  : programming.haskell
summary    : A quasiquoter for neat and simple multiline text interpolation
description: |
    A quasiquoter for neat and simple multiline text interpolation
builddeps  :
    - haskell-base-prelude-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-base-prelude-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
